name: middleware
description: Modern middleware on Future
version: 1.0.0
homepage: https://github.com/TGXed/middleware
repository: https://github.com/TGXed/middleware
issue_tracker: https://github.com/TGXed/middleware/issues

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
